version: '3.4'

services:
  m183-shovel-knight-security:
    image: ${DOCKER_REGISTRY-}m183shovelknightsecurity
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      -  shovel-knight-mssql
    ports:
      - '5001:5001'
    environment:
     - ASPNETCORE_URLS=https://0.0.0.0:5001
     - ASPNETCORE_HTTPS_PORT=5001
  shovel-knight-mssql:
    image: microsoft/mssql-server-linux:latest
    container_name: skmssql
    volumes:
        - shovel-knight-data:/var/opt/mssql/data
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=my-secret-pw-xD
    ports:
        - "1433:1433"

volumes:
  shovel-knight-data: